<?php

/**
 * View
 *
 * @category  CodeBlender
 * @package   Template
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
// Register Placeholders
$this->title = 'Facebook Helpers';

echo 'Check out the Facebook URL Linter for Open Graph Tags - http://developers.facebook.com/tools/debug/og/object?q=triangle-solutions.com';

// Facebook Activity Feed
echo '<hr />Facebook Activity Feed<br />';
echo $this->facebook_ActivityFeed();

// Facebook Add To Timeline
echo '<hr />Facebook Add To Timeline<br />';
echo $this->facebook_AddToTimeline();

// Facebook Comments
echo '<hr />Facebook Comments<br />';
echo $this->facebook_Comments();

// Facebook Facepile
echo '<hr />Facebook Facepile<br />';
echo $this->facebook_Facepile();

// Facebook Like Box
echo '<hr />Facebook Like Box<br />';
echo $this->facebook_LikeBox();

// Facebook Like Button
echo '<hr />Facebook Like Button<br />';
echo $this->facebook_LikeButton();

// Facebook Live Stream
echo '<hr />Facebook Live Stream<br />';
echo $this->facebook_LiveStream();

// Facebook Login Button
echo '<hr />Facebook Login Button<br />';
echo $this->facebook_LoginButton();

// Facebook Recommendations
echo '<hr />Facebook Recomendations<br />';
echo $this->facebook_Recommendations();

// Facebook Recommendations Bar
echo '<hr />Facebook RecomendationsBar<br />';
echo $this->facebook_RecommendationsBar();

// Facebook Recommendations Box
echo '<hr />Facebook Recomendations Box<br />';
echo $this->facebook_RecommendationsBox();

// Facebook Registration
echo '<hr />Facebook Registration<br />';
echo $this->facebook_Registration();

// Facebook Send Button
echo '<hr />Facebook Send Button<br />';
echo $this->facebook_SendButton();

