<?php

/**
 * View
 *
 * @category  CodeBlender
 * @package   Template
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
// Register Placeholders
$this->title = 'Social Helpers';

// Add This
echo $this->addThis();

// Get Satisfaction
echo $this->getSatisfaction();

// Tweet Button
echo $this->tweetButton();

// Wibiya Toolbar
echo $this->wibiya();
