<?php
/**
 * Footer
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
?>

<div id="footer">

    <div class="footerContent">

        <div class="floatLeft">

            <p>
                &copy;<?php echo date('Y'); ?>
                <img src="<?php echo $this->themePath; ?>/images/template/triangle-logo.png" height="14" width="16" />
                A <a href="http://www.triangle-solutions.com/">Triangle Solutions Ltd</a> Production |
                <img src="<?php echo $this->themePath; ?>/images/template/telephone.png" height="16" width="16" /><a href="http://www.triangle-solutions.com/users/contact">Contact Us</a>
            </p>

            <p class="footerSmall">
                Version 1.0.0 | <a href="http://www.triangle-solutions.com/privacy">Privacy Policy</s>
            </p>

        </div>

        <p class="floatRight">
            <?php echo $this->layout_CodeBlender(); ?>
        </p>

    </div>

    <div class="clear"></div>

</div>
