<?php
/**
 * Layout
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2000-2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 *
 * @todo make Charset configurable from the config
 * @todo Add page class to the body for overiding purposes
 */
// Create the Doctype as Strict
echo $this->doctype('HTML5');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
    <head>

        <?php
        // Header
        try {
            $this->header();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }

        // Charset
        echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');

        // Title
        echo $this->headTitle($this->title);

        // Stylesheet - Favicon
        echo $this->headLink()
                ->appendStylesheet($this->themePath . '/css/admin.css', 'screen')
                ->appendStylesheet($this->cssPath . '/main.css', 'screen')
                ->headLink(array('rel' => 'favicon', 'href' => $this->imagePath . '/favicon.ico'), 'PREPEND');

        // Extra Style and Scripts
        echo $this->headStyle();
        echo $this->headScript();
        ?>

    </head>
    <body>

        <?php
        // Facebook SDK Helper
        try {
            echo $this->facebook_JavascriptSDK();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <div id="wrapper">

            <div id="header">
                <h1><?php echo $this->siteTitle; ?></h1>
            </div>

            <div id="info">
            </div>

            <div id="content">

                <!--                <ul id="adminNav">

                                    <li id="navDashboard" class="iconDashboard">

                                        <div class="menuImage">
                                            <a href="index.php"><br></a>
                                        </div>

                                        <div class="wp-menu-toggle"><br></div>

                                        <a tabindex="1" class="iconDashboard" href="index.php">Dashboard</a>

                                        <div class="subNav">

                                            <ul>
                                                <li class="wp-first-item">
                                                    <a tabindex="1" class="wp-first-item" href="index.php">Dashboard</a>
                                                </li>
                                                <li>
                                                    <a tabindex="1" href="update-core.php">Updates
                                                        <span title="1 WordPress Update, 2 Plugin Updates" class="update-plugins count-3">
                                                            <span class="update-count">3</span>
                                                        </span>
                                                    </a>
                                                </li>
                                            </ul>

                                        </div>
                                    </li>
                                </ul>-->

                <div id="nav">
                    <?php echo $this->navigation()->menu(); ?>
                </div>

                <div id="mainContent">
                    <?php echo $this->layout()->content; ?>
                </div>

                <div class="clear"></div>

            </div>

        </div>

        <?php echo $this->render('footer.phtml'); ?>

    </body>

</html>
